name: Python Release

on:
  push:
    tags: [ 'v[0-9]*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      project-name: ${{ vars.PYPI_PROJECT_NAME || github.event.repository.name }}
      project-version: ${{ steps.check-version.outputs.project-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version-file: '.tool-versions'
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Check version
        id: check-version
        run: |
          version="$(uv version --short)"
          if ! [[ "${GITHUB_REF_NAME#v}" == "$version" ]]; then
            printf >&2 %s\\n 'ERROR: Git tag does not match project version'
            exit 1
          fi
          printf 'project-version=%s\n' "$version" >> "$GITHUB_OUTPUT"
      - name: Build project
        run: ./Taskfile build
      - name: Smoke test (wheel)
        run: ./Taskfile test-artifact dist/*.whl
      - name: Smoke test (source distribution)
        run: ./Taskfile test-artifact dist/*.tar.gz
      - name: Generate release information
        run: ./Taskfile generate-release-information
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/

  publish-github:
    needs: build
    if: ${{ ! contains(github.ref_name, '.dev') }}
    runs-on: ubuntu-latest
    environment:
      name: github-releases
      url: ${{ format('https://github.com/{0}/releases', github.repository) }}
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: release-dists
          path: dist/
      - name: Prepare release information
        run: |
          printf 'RELEASE_VERSION=%s\n' "${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          sed 1d -- dist/RELEASE-*.md > RELEASE.md
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.event.repository.name }} ${{ env.RELEASE_VERSION }}
          body_path: RELEASE.md
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'c') }}
          fail_on_unmatched_files: true
          working_directory: dist
          files: |
            *.whl
            *.tar.gz

  publish-pypi:
    needs: build
    if: ${{ ! contains(github.ref_name, '.dev') }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: ${{ format('https://pypi.org/project/{0}', vars.PYPI_PROJECT_NAME || github.event.repository.name) }}
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: release-dists
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
